const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);

    if (args.len != 3) {
        std.debug.print("Usage: {s} <hacks-dir> <output-file>\n", .{args[0]});
        return error.InvalidArguments;
    }

    const hacks_dir_path = args[1];
    const output_path = args[2];

    var hack_files: std.ArrayList([]const u8) = .empty;
    defer {
        for (hack_files.items) |name| {
            allocator.free(name);
        }
        hack_files.deinit(allocator);
    }

    var hacks_dir = try openIterableDir(hacks_dir_path);
    defer hacks_dir.close();

    var iter = hacks_dir.iterate();
    while (try iter.next()) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.name, ".zig")) continue;

        const name_copy = try allocator.dupe(u8, entry.name);
        try hack_files.append(allocator, name_copy);
    }

    std.mem.sort([]const u8, hack_files.items, {}, struct {
        fn lessThan(_: void, lhs: []const u8, rhs: []const u8) bool {
            return std.mem.lessThan(u8, lhs, rhs);
        }
    }.lessThan);

    var output_file = try createFile(output_path);
    defer output_file.close();

    var output_buffer: [4096]u8 = undefined;
    var file_writer = output_file.writer(&output_buffer);
    const writer = &file_writer.interface;

    try writer.writeAll("// This file is auto-generated by tools/gen_hacks.zig. Do not edit manually.\n");
    try writer.writeAll("const AppContext = @import(\"app_context.zig\").AppContext;\n\n");
    try writer.print("pub const hack_count: usize = {};\n\n", .{hack_files.items.len});

    try writer.writeAll("pub const Storage = struct {\n");
    for (hack_files.items, 0..) |file_name, index| {
        try writer.print("    hack_{d}: @import(\"hacks/{s}\").HackImpl,\n", .{ index, file_name });
    }
    try writer.writeAll("};\n\n");

    try writer.writeAll("pub fn initStorage(storage: *Storage, app: *AppContext) void {\n");
    if (hack_files.items.len == 0) {
        try writer.writeAll("    _ = app;\n");
        try writer.writeAll("    storage.* = .{};\n");
    } else {
        try writer.writeAll("    storage.* = .{\n");
        for (hack_files.items, 0..) |_, index| {
            try writer.print("        .hack_{d} = .{{ .app = app }},\n", .{index});
        }
        try writer.writeAll("    };\n");
    }
    try writer.writeAll("}\n");
    try writer.flush();
}

fn openIterableDir(path: []const u8) !std.fs.Dir {
    if (std.fs.path.isAbsolute(path)) {
        return std.fs.openDirAbsolute(path, .{ .iterate = true });
    }
    return std.fs.cwd().openDir(path, .{ .iterate = true });
}

fn createFile(path: []const u8) !std.fs.File {
    if (std.fs.path.isAbsolute(path)) {
        return std.fs.createFileAbsolute(path, .{ .truncate = true });
    }
    return std.fs.cwd().createFile(path, .{ .truncate = true });
}
